### ISSUE TITLE
normal generation

### ISSUE THREAD

**Issue by dukeeeey** [syoyo/tinyobjloader#29] opened 2015-02-17 22:35 UTC
It would be really great if the library could generate normals, based on the smoothing groups, if the model itself doesn't contain any normals.

**Comment by syoyo** [comment] 2015-02-18 03:50
I can compute smooth vertex normal, but don't know to compute normal using the smoothing groups. Do you have any idea?

**Comment by dukeeeey** [comment] 2015-02-18 10:07
Hi, thanks for your reply. Smoothing groups work like this -> http://i.imgur.com/YHxnW9d.png
Normals are only averaged together with faces that share the same smoothing group. It's so you can give models hard edges, instead of everything being rounded. Final result looks like -> http://img.photobucket.com/albums/v224/elbazo/minitut.jpg 
http://www.3dmax-tutorials.com/graphics/il_smoothing_groups.jpg

Lib3ds has a function that does something very similar to what we want.

void lib3ds_mesh_calculate_vertex_normals(Lib3dsMesh *mesh, float (*normals)[3])
https://code.google.com/p/lib3ds/source/browse/trunk/src/lib3ds_mesh.c

**Comment by syoyo** [comment] 2015-02-19 13:14
Thanks. I think I understand how smoothing groups works and how to implement it, but may need some time. And I highly appreciate if you give us test .obj models which uses smoothing groups.

**Comment by dukeeeey** [comment] 2015-02-19 14:09
Hi,
The spec for OBJ has some examples

1.      Cube with group names

The following example is a cube with each of its faces placed in a
separate group. In addition, all elements belong to the group cube.

    v 0.000000 2.000000 2.000000
    v 0.000000 0.000000 2.000000
    v 2.000000 0.000000 2.000000
    v 2.000000 2.000000 2.000000
    v 0.000000 2.000000 0.000000
    v 0.000000 0.000000 0.000000
    v 2.000000 0.000000 0.000000
    v 2.000000 2.000000 0.000000
    # 8 vertices

    g front cube
    f 1 2 3 4
    g back cube
    f 8 7 6 5
    g right cube
    f 4 3 7 8
    g top cube
    f 5 1 4 8
    g left cube
    f 5 6 2 1
    g bottom cube
    f 2 6 7 3
    # 6 elements


2.      Two adjoining squares with a smoothing group

This example shows two adjoining squares that share a common edge. The
squares are placed in a smoothing group to ensure that their common
edge will be smoothed when rendered with Image.

    v 0.000000 2.000000 0.000000
    v 0.000000 0.000000 0.000000
    v 2.000000 0.000000 0.000000
    v 2.000000 2.000000 0.000000
    v 4.000000 0.000000 -1.255298
    v 4.000000 2.000000 -1.255298
    # 6 vertices

    g all
    s 1
    f 1 2 3 4
    f 4 3 5 6
    # 2 elements


3.      Two adjoining squares with vertex normals

This example also shows two squares that share a common edge. Vertex
normals have been added to the corners of each square to ensure that
their common edge will be smoothed during display in Model and PreView
and when rendered with Image.

    v 0.000000 2.000000 0.000000
    v 0.000000 0.000000 0.000000
    v 2.000000 0.000000 0.000000
    v 2.000000 2.000000 0.000000
    v 4.000000 0.000000 -1.255298
    v 4.000000 2.000000 -1.255298
    vn 0.000000 0.000000 1.000000
    vn 0.000000 0.000000 1.000000
    vn 0.276597 0.000000 0.960986
    vn 0.276597 0.000000 0.960986
    vn 0.531611 0.000000 0.846988
    vn 0.531611 0.000000 0.846988
    # 6 vertices

    # 6 normals

    g all
    s 1
    f 1//1 2//2 3//3 4//4
    f 4//4 3//3 5//

If you need any more let me know and I'll try and dig out some

**Comment by penberg** [comment] 2016-01-31 15:29
@syoyo, @dukeeeey, any update on this issue? It would very useful feature indeed.

**Comment by syoyo** [comment] 2016-02-01 03:04
Still no one is working on this. You can contribute a patch!

**Comment by chrisliebert** [comment] 2016-02-01 08:45
Here is an example implementation for flat shading. It can be placed before the final return statement of LoadOBJ(...)  and by adding generateNormals as another optional boolean parameter to LoadOBJ(,,,). The method used for surface normal calculation is described here: https://support.microsoft.com/en-us/kb/131130 and the result is then scaled to a unit vector.
```
   if(generateNormals) {
	  // Ensure there are no normals loaded
	  vn.clear();
	  for (size_t i = 0; i < shapes.size(); i++) {
		  assert((shapes[i].mesh.positions.size() % 3) == 0);
		  float nx, ny, nz = 0.0f; // normal for current triangle
		  float vx1, vx2, vx3 = 0.f; // vertex 1
		  float vy1, vy2, vy3 = 0.f; // vertex 2
		  float vz1, vz2, vz3 = 0.f; // vertex 3
		  for (size_t v = 0; v < shapes[i].mesh.positions.size() / 3; v++) {
			  float x = shapes[i].mesh.positions[3.f*v];
			  float y = shapes[i].mesh.positions[3.f*v+1];
			  float z = shapes[i].mesh.positions[3.f*v+2];
			  switch(v % 3) {
			  case 0:
				  // Defining first point in triangle
				  vx1 = x;
				  vy1 = y;
				  vz1 = z;
				  break;
			  case 1:
				  // Defining second point in triangle
				  vx2 = x;
				  vy2 = y;
				  vz2 = z;
				  break;
			  case 2:
				  // Defining third point in a triangle
				  vx3 = x;
				  vy3 = y;
				  vz3 = z;
				  float qx, qy, qz, px, py, pz;
				  // Calculate q vector
				  qx = vx2 - vx1;
				  qy = vy2 - vy1;
				  qz = vz2 - vz1;
				  // Calculate p vector
				  px = vx3 - vx1;
				  py = vy3 - vy1;
				  pz = vz3 - vz1;
				  // Calculate normal
				  nx = py * qz - pz * qy;
				  ny = pz * qx - px * qz;
				  nz = px * qy - py * qx;
				  // Scale to unit vector
				  float s = sqrt(nx*nx + ny*ny + nz*nz);
				  nx /= s;
				  ny /= s;
				  nz /= s;
				  // Add the normal 3 times (once for each vertex)
				  for(int j=0; j<3; j++) {
					  shapes[i].mesh.normals.push_back(nx);
					  shapes[i].mesh.normals.push_back(ny);
					  shapes[i].mesh.normals.push_back(nz);
				  }
				  break;
			  }
		  }
	  }
  }
```

*Some modifications will be necessary to support non-triangular meshes.

**Comment by syoyo** [comment] 2016-02-02 01:52
Yeah, simple flat or smooth normal calculation is rather easy. How about getting smooth shading normal using smoothing groups, @chrisliebert ? (We need to add support for parsing smoothing groups tag firstly, though)

**Comment by chrisliebert** [comment] 2016-02-02 08:22
This is the approach I had in mind, might take while to get right. 
1. calculate normals with flat shading (or preserve values from .obj)
2. iterate over each smoothing group (with tag) and perform the following:
- construct a list of triangle edges (an edge contains two indices that represent the shared vertices)
- iterate through the edges and recalculate the normal for each vertex by taking the sum of the two flat normal vectors and dividing by the length of their sum to produce a "smooth" unit vector

Thoughts:
*Updating the normals in-place could cause issues on vertices that intersect multiple edges so those vertices with n edges need to be smoothed n-1 times  

*The entire process should be re-entrant since each edge will have two vertices with the same normal already, so recomputing their average will not change the values after the algorithm is applied initially.

**Comment by syoyo** [comment] 2016-02-03 04:22
> The entire process should be re-entrant

I guess you can simply allocate another buffer for smooth normal(its OK to consume moderate memory amount in tinyobjloader)

**Comment by gopalss** [comment] 2018-01-29 04:09
I tried out an idea and it seems to work. It consists of the following steps. The first three steps are changes in tiny_object_loader.h. The others are changes in viewer.cc.

Step 1: Add an int parameter called "smoothingGroupId" to the struct mesh_t, which is part of the struct shape_t. The idea is to have all elements in a shapt_t have the same smoothingGroupId. This is the only change to the overall data structure.

Step 2: In the LoadObj function, add code to process the case of token[0] == 's'. Get the smoothing group id. If it is same as the previous smoothing id, continue. If not, export the current face group and start a new group. For the new group, reset the shape to have the new smoothing group id. Keep the material, tag and name as such.

Step 3: In a few other places in tiny_object_loader.h, wherever exportFaceGroupToShape is called and shape is reset, preserve the smoothingGroupId of the shape.

Step 4: In the function LoadObjAndConvert of viewer.cc:  Add the following code in the beginning (inside) of the for loop for (size_t s = 0; s < shapes.size(); s++) : 

			// Check for smoothing group and compute smoothing normals
			std::map<int, float[3]> smoothVertexNormals;
			if (shapes[s].mesh.smoothingGroupId > 0)
				computeSmoothingNormals(attrib, shapes[s], smoothVertexNormals);

computeSmoothingNormals is a new function I wrote, that is similar to the one suggested by chrisliebert on Feb 1 2016.  It computes the average of the face normals at each vertex of the current shape. The computed average normals are stored in smoothVertexNormals, which maps a vertex id to a normal.

Step 5: At the time of computing the normals, n[3][3] inside the for loop for (size_t f = 0; f < shapes[s].mesh.indices.size() / 3; f++) in the same function of the above step: Before going to compute geometric normal,  add an else if statement as follows: 
     else if (!smoothVertexNormals.empty())
     {
            // assign the vertex normals that have been computed and stored in Step 4.
     }

That is it. I tried this for the second example of dukeeeey - Feb 19 2015 and got the following image, before smoothing and after smoothing.


![smoothingexpt](https://user-images.githubusercontent.com/35585921/35493285-1396734c-0480-11e8-961a-9f78aa974a8a.png)

**Comment by syoyo** [comment] 2018-01-29 06:12
Awesome @gopalss !

Your idea looks promising, so could you please send PR of smoothing support?

**Comment by toastedcrumpets** [comment] 2018-01-29 21:20
Hi @gopalss! It looks like your new to github, and I'd really like this change. If you need a hand getting a pull request (PR) together I will help you out if needed. You can even just dump the repo to me via email m.campbellbannerman@abdn.ac.uk and I'll create the patch for discussion.

**Comment by gopalss** [comment] 2018-01-30 02:43
Hi Marcus,

 I have used a little bit of GitHub in my previous job. I am relatively new
to personal GitHub. So it took me some time to set up my GitHub, fork
Soyoyo's repository and create a PR. I have done that now - PR #162. Please
check. It does not give me the option to add reviewers. That button is not
active. You can tell me if there is a way to add Soyoyo and you as
reviewers.

If you are not able to see my PR, I shall make my changes available in some
other way.

Thanks
Gopal.

**Comment by syoyo** [comment] 2018-02-04 05:23
Smoothing group  support and smoothing normal calculation is now  in `master` branch based on @gopalss 's PR(smoothing normal calculation is done in`viewer` example).

I have at least confirmed it works well with this test set: https://github.com/syoyo/tinyobjloader/blob/master/models/smoothing-group-two-squares.obj

So I close this issue.

**Closed by syoyo** 2018-02-04 05:23 UTC
Labels: enhancement
